### ISSUE TITLE
installation too complicated

### ISSUE THREAD

**Issue by yannickwurm** [monicadragan/GeneValidator#16]
1. Additional requirement: ruby-dev is required (on Ubuntu 14.04) 
2. additional requirement: nokogiri gem. 

nokogiri can be challenging to install manually (it was on Tim's 14.04). 

Take home message: installation needs to be easier. 
E.g. add a bundler `bundle install` step

And/or make a full gem that can be installed via  `gem install genevalidator-alpha`

**Comment by IsmailM** [comment]
Addressed in PR #54
