### ISSUE TITLE
get_raw_sequences script required?

### ISSUE THREAD

**Issue by yannickwurm** [monicadragan/GeneValidator#32]
Hi Monica,

small question. if I understand correctly there are 3 usage scenarios for GV: 

1. Have 3 sequences; do BLAST remotely... get hit sequences
     from NCBI
2. have many sequences; run BLAST separately; user gives BLAST output
     to GV as input. AND user gives FASTA of BLAST DB (or just hits) to GV
3. have many sequences; let GV handle everything (including
     locally running BLAST on local db). 

In which scenario is the `get_raw_sequences` script required? @ismailm & I are a bit confused about when & why it is necessary. 

Thanks,
Yannick

**Comment by IsmailM** [comment]
Addressed in PR #54
