### ISSUE TITLE
RubyGems convention

### ISSUE THREAD

**Issue by yeban** [monicadragan/GeneValidator#58]
* `lib/validation.rb` should be `lib/genevalidator.rb`. It's expected that after `gem install foo`, I should be able to `require 'foo'` in irb or a Ruby script. However in this case, I `gem install genevalidator`, but `require 'validation'`.
* Similarly, `class Validation` in `lib/validation.rb` should be `class GeneValidator`.
* The convention is that each gem should introduce only one top-level class / module, the same as gem name. But all classes in GeneValidator are top-level. They should all be nested within `GeneValidator` class. So `Output` should be `GeneValidator::Output` and so on.

**Comment by IsmailM** [comment]
I'm not sure if I have fully addressed this...

I have created a GeneValidator module which contains the Validation Class and all other classes...

@yeban Can you please take a look at the Code at the alpha branch (see [here](https://github.com/monicadragan/GeneValidator/tree/alpha)) and let me if you would like me to make any other changes...

If not, can you please close this issue. (After this, I'll create a pull request to merge the alpha into the master)...

**Comment by yeban** [comment]
Had a quick look. Looks good.
