### ISSUE TITLE
arg validation - blast database

### ISSUE THREAD

**Issue by yeban** [monicadragan/GeneValidator#66]
> https://github.com/monicadragan/GeneValidator/blob/master/lib/genevalidator/arg_validation.rb#L114

BLAST db is not required if `blast_xml_file` and `raw_sequences` options are set, right?

I guess this would be important if CLI allows specifying `raw_sequences` (like before?)

**Comment by IsmailM** [comment]
Yes, I agree.

It is currently in alpha branch...

Since I have not yet fully tested everything on the alpha branch I may just bring a few features (including this `raw_sequences` option) into the master.

**Comment by IsmailM** [comment]
see the latest version (version 1.5.5)....

Install as follows...
   `$ gem install GeneValidator`
